name: FranticGod
main: org.frantictools.franticgod.FranticGod
version: 1.0

commands:
   godsays:
      description: Speak with the word of god.
      permission: franticgod.godsays
      usage: |
        /godsays <text>
permissions:
    franticgod.*:
        description: Gives access to all franticgod stuff.
        children:
            franticgod.immune: true
            franticgod.godsays: true
    franticgod.immune:
        description: Immune to franticgod
        default: op
    franticgod.godsays:
        description: Allows you to use the /godsays command
        default: op
    franticgod.godban:
        description: Allows you to use the /godban command
        default: op